# Generated by Django 3.0.6 on 2020-09-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0003_auto_20200922_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
