# Generated by Django 3.1.1 on 2020-09-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0004_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prices', models.JSONField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_price_history', to='TCGTrackingTool.card')),
            ],
        ),
    ]
