# Generated by Django 3.1.1 on 2020-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0007_auto_20201012_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricenotification',
            name='card_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
