# Generated by Django 3.1.1 on 2020-10-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0009_cardpricenotificationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricenotificationmessage',
            name='card_edition',
            field=models.CharField(default='heelo', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpricenotificationmessage',
            name='card_name',
            field=models.CharField(default='heeelo', max_length=60),
            preserve_default=False,
        ),
    ]
