# Generated by Django 3.1.1 on 2020-11-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0010_auto_20201019_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
