# Generated by Django 3.1.1 on 2020-11-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0011_card_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='latest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='latest_price_card_type',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
