# Generated by Django 3.1.1 on 2020-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0012_auto_20201127_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='latest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='latest_price_card_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
