# Generated by Django 3.1.1 on 2020-11-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCGTrackingTool', '0013_auto_20201127_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricehistory',
            name='prices',
            field=models.CharField(max_length=500),
        ),
    ]
